# EffectRegistry.gd
extends Node

# Design-time list of every effect handler script. Preloaded explicitly instead
# of scanning res://Resources/Effects/Handlers/ at runtime via DirAccess — in
# exported builds, .gd files are remapped/compiled, so filename-based discovery
# silently finds nothing and the registry comes up empty (this is why fire never
# spread in exports). Preloading resolves at compile time; nothing left to fail.
#
# This block is regenerated by Tools/GenerateEffectRegistry.gd — run it from the
# editor after adding or removing a handler script.
# --- AUTO-GENERATED HANDLERS LIST START ---
const HANDLER_SCRIPTS: Array[GDScript] = [
	preload("res://Resources/Effects/Handlers/AttackDownHandler.gd"),
	preload("res://Resources/Effects/Handlers/AttackUpHandler.gd"),
	preload("res://Resources/Effects/Handlers/BerserkHandler.gd"),
	preload("res://Resources/Effects/Handlers/BlazingHandler.gd"),
	preload("res://Resources/Effects/Handlers/BlindHandler.gd"),
	preload("res://Resources/Effects/Handlers/BurningHandler.gd"),
	preload("res://Resources/Effects/Handlers/CharmHandler.gd"),
	preload("res://Resources/Effects/Handlers/ConfuseHandler.gd"),
	preload("res://Resources/Effects/Handlers/CritDownHandler.gd"),
	preload("res://Resources/Effects/Handlers/CritUpHandler.gd"),
	preload("res://Resources/Effects/Handlers/DefenseDownHandler.gd"),
	preload("res://Resources/Effects/Handlers/DefenseUpHandler.gd"),
	preload("res://Resources/Effects/Handlers/DisableHandler.gd"),
	preload("res://Resources/Effects/Handlers/DiseasedHandler.gd"),
	preload("res://Resources/Effects/Handlers/DoomHandler.gd"),
	preload("res://Resources/Effects/Handlers/ElectrifiedConductedHandler.gd"),
	preload("res://Resources/Effects/Handlers/ElectrifiedHandler.gd"),
	preload("res://Resources/Effects/Handlers/FeatherHandler.gd"),
	preload("res://Resources/Effects/Handlers/FloatHandler.gd"),
	preload("res://Resources/Effects/Handlers/FrozenHandler.gd"),
	preload("res://Resources/Effects/Handlers/HasteHandler.gd"),
	preload("res://Resources/Effects/Handlers/ImmobilizeHandler.gd"),
	preload("res://Resources/Effects/Handlers/InductionHandler.gd"),
	preload("res://Resources/Effects/Handlers/InvisibleHandler.gd"),
	preload("res://Resources/Effects/Handlers/MagicDownHandler.gd"),
	preload("res://Resources/Effects/Handlers/MagicUpHandler.gd"),
	preload("res://Resources/Effects/Handlers/MagnetisedHandler.gd"),
	preload("res://Resources/Effects/Handlers/PetrifyHandler.gd"),
	preload("res://Resources/Effects/Handlers/PoisonHandler.gd"),
	preload("res://Resources/Effects/Handlers/ProtectHandler.gd"),
	preload("res://Resources/Effects/Handlers/RedHotHandler.gd"),
	preload("res://Resources/Effects/Handlers/ReflectHandler.gd"),
	preload("res://Resources/Effects/Handlers/RegenHandler.gd"),
	preload("res://Resources/Effects/Handlers/ShellHandler.gd"),
	preload("res://Resources/Effects/Handlers/SilenceHandler.gd"),
	preload("res://Resources/Effects/Handlers/SleepHandler.gd"),
	preload("res://Resources/Effects/Handlers/SlipperyHandler.gd"),
	preload("res://Resources/Effects/Handlers/SlowHandler.gd"),
	preload("res://Resources/Effects/Handlers/SoakedHandler.gd"),
	preload("res://Resources/Effects/Handlers/SpeedDownHandler.gd"),
	preload("res://Resources/Effects/Handlers/SpeedUpHandler.gd"),
	preload("res://Resources/Effects/Handlers/SquishedHandler.gd"),
	preload("res://Resources/Effects/Handlers/StaggeredHandler.gd"),
	preload("res://Resources/Effects/Handlers/StopHandler.gd"),
]
# --- AUTO-GENERATED HANDLERS LIST END ---

var _handlers: Dictionary = {}

func _ready() -> void:
	_load_handlers()

func _load_handlers() -> void:
	for script in HANDLER_SCRIPTS:
		var instance = script.new()
		var effect_id = instance.get_effect_id()
		if effect_id != EffectId.Id.NONE:
			_handlers[effect_id] = instance

	_assert_full_coverage()

func _assert_full_coverage() -> void:
	for id in EffectId.Id.values():
		if id == EffectId.Id.NONE:
			continue
		if not _handlers.has(id):
			push_warning("EffectRegistry: no handler registered for effect_id " + EffectId.Id.keys()[id])

func get_handler(effect_id: EffectId.Id) -> EffectHandler:
	return _handlers.get(effect_id, null)

func get_all_handlers() -> Dictionary:
	return _handlers
