extends Node

# Design-time list of every equipment piece. Preloaded explicitly — same
# export-safety reasoning as every other registry.
#
# This block is regenerated by Tools/GenerateEquipmentRegistry.gd — run it
# after adding, removing, or moving any equipment .tres file.
# --- AUTO-GENERATED EQUIPMENT LIST START ---
const EQUIPMENT: Array[EquipmentData] = [
	preload("res://Data/Equipment/Armor/Bronze_Plate.tres"),
	preload("res://Data/Equipment/Weapons/Bronze_Sword.tres"),
]
# --- AUTO-GENERATED EQUIPMENT LIST END ---

var _equipment: Dictionary = {}

func _ready() -> void:
	for piece in EQUIPMENT:
		if piece != null:
			if _equipment.has(piece.equipment_id):
				push_error("EquipmentRegistry: duplicate equipment_id %d ('%s' vs '%s')" % [
					piece.equipment_id, piece.equipment_name, _equipment[piece.equipment_id].equipment_name])
			_equipment[piece.equipment_id] = piece

func get_equipment(equipment_id: int) -> EquipmentData:
	return _equipment.get(equipment_id, null)
